git submodule deinit --force -- "UI/frontend-plugins/streamfx/cmake/clang"
git submodule add --force -b master --name "UI/frontend-plugins/streamfx/cmake/clang" -- "https://github.com/Xaymar/cmake-clang.git" "UI/frontend-plugins/streamfx/cmake/"
git submodule set-url -- "UI/frontend-plugins/streamfx/cmake/" "https://github.com/Xaymar/cmake-clang.git"
git submodule deinit --force -- "UI/frontend-plugins/streamfx/cmake/version"
git submodule add --force -b master --name "UI/frontend-plugins/streamfx/cmake/version" -- "https://github.com/Xaymar/cmake-version.git" "UI/frontend-plugins/streamfx/cmake/version"
git submodule set-url -- "UI/frontend-plugins/streamfx/cmake/version" "https://github.com/Xaymar/cmake-version.git"
git submodule deinit --force -- "UI/frontend-plugins/streamfx/third-party/nlohmann-json"
git submodule add --force -b master --name "UI/frontend-plugins/streamfx/third-party/nlohmann-json" -- "https://github.com/nlohmann/json.git" "UI/frontend-plugins/streamfx/third-party/nlohmann-json"
git submodule set-url -- "UI/frontend-plugins/streamfx/third-party/nlohmann-json" "https://github.com/nlohmann/json.git"
git submodule deinit --force -- "UI/frontend-plugins/streamfx/third-party/msvc-redist-helper"
git submodule add --force -b master --name "UI/frontend-plugins/streamfx/third-party/msvc-redist-helper" -- "https://github.com/Xaymar/msvc-redist-helper.git" "UI/frontend-plugins/streamfx/third-party/msvc-redist-helper"
git submodule set-url --  "UI/frontend-plugins/streamfx/third-party/msvc-redist-helper" "https://github.com/Xaymar/msvc-redist-helper.git
git submodule deinit --force -- "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-ar-sdk"
git submodule add --force -b master --name "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-ar-sdk" -- "https://github.com/NVIDIA/MAXINE-AR-SDK.git" "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-ar-sdk"
git submodule set-url -- "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-ar-sdk" "https://github.com/NVIDIA/MAXINE-AR-SDK.git"
git submodule deinit --force -- "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-vfx-sdk"
git submodule add --force -b master --name "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-vfx-sdk" -- "https://github.com/NVIDIA/MAXINE-VFX-SDK.git" "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-vfx-sdk"
git submodule set-url -- "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-vfx-sdk" "https://github.com/NVIDIA/MAXINE-VFX-SDK.git"
git submodule deinit --force -- "UI/frontend-plugins/streamfx/third-party/obs-studio"
git submodule add --force -b master --name "UI/frontend-plugins/streamfx/third-party/obs-studio" -- "https://github.com/obsproject/obs-studio.git" "UI/frontend-plugins/streamfx/third-party/obs-studio"
git submodule set-url -- "UI/frontend-plugins/streamfx/third-party/obs-studio" "https://github.com/obsproject/obs-studio.git"
git submodule deinit --force -- "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-afx-sdk"
git submodule add --force -b master --name "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-afx-sdk" -- "https://github.com/NVIDIA/MAXINE-AFX-SDK.git" "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-afx-sdk"
git submodule set-url -- "UI/frontend-plugins/streamfx/third-party/nvidia-maxine-afx-sdk" "https://github.com/NVIDIA/MAXINE-AFX-SDK.git"
