// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2023 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "gs-limits.hpp"

namespace streamfx::obs::gs {
	struct vertex {
		vec3*     position;
		vec3*     normal;
		vec3*     tangent;
		uint32_t* color;
		vec4*     uv[MAXIMUM_UVW_LAYERS];

		explicit vertex();
		vertex(const vertex& other) : vertex(other.position, other.normal, other.tangent, other.color, other.uv) {}
		vertex(vec3* const p, vec3* const n, vec3* const t, uint32_t* const col, vec4* const uv[MAXIMUM_UVW_LAYERS]);
		~vertex();

		private:
		bool  _has_store;
		void* _store;
	};
} // namespace streamfx::obs::gs
