name: Check Code Formatting 🛠️
on:
  workflow_call:

env:
  ENABLE_QT_CHECKS: false
  ENABLE_SWIFT_CHECKS: false
  ENABLE_FLATPAK_CHECKS: false

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: clang-format Check 🐉
        id: clang-format
        uses: ./.github/actions/run-clang-format
        with:
          failCondition: error

  swift-format:
    if: env.ENABLE_SWIFT_CHECKS == 'true'
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: swift-format Check 🔥
        id: swift-format
        uses: ./.github/actions/run-swift-format
        with:
          failCondition: error

  cmake-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cmake-format Check 🎛️
        id: cmake-format
        uses: ./.github/actions/run-cmake-format
        with:
          failCondition: error

  flatpak-validator:
    if: env.ENABLE_FLATPAK_CHECKS == 'true'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Flatpak Manifest Check 📦
        id: flatpak-check
        uses: ./.github/actions/flatpak-manifest-validator
        with:
          failCondition: error

  qt-xml-validator:
    if: env.ENABLE_QT_CHECKS == 'true'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Qt XML Check 🖼️
        id: qt-xml-check
        uses: ./.github/actions/qt-xml-validator
        with:
          failCondition: error
